Add enable-threads=true to the config file before restarting waptserver

diff --git a/waptserver/deb/DEBIAN/postinst b/waptserver/deb/DEBIAN/postinst
--- a/waptserver/deb/DEBIAN/postinst
+++ b/waptserver/deb/DEBIAN/postinst
@@ -12,35 +12,6 @@ chown wapt:www-data -R /opt/wapt/
 
 update-rc.d waptserver defaults
 
-if [ -f "/opt/wapt/waptserver/waptserver.ini" ]
-then
-  if ps aux | grep -q wapt
-  then
-    [ -f /etc/init.d/waptserver ] && /etc/init.d/waptserver stop
-    # XXX temporary: clean up leftover waptserver processes
-    # due to broken /etc/init.d/waptserver script
-    pkill -INT -f '^/usr/bin/uwsgi-core.*wapt'
-    [ -f /etc/init.d/waptserver ] && /etc/init.d/waptserver start
-  else
-    [ -f /etc/init.d/waptserver ] && /etc/init.d/waptserver start
-  fi
-else
-    printf '\e[1;31m%-6s\e[m\n' "The installation of waptserver is finished !!"
-    printf '\e[1;31m%-6s\e[m\n' "For postconf please run: /usr/bin/python /opt/wapt/waptserver/scripts/postconf.py"
-fi
-
-# Backward compat
-agent=/var/www/wapt/waptagent.exe
-setup=/var/www/wapt/waptsetup.exe
-
-if [ -e "$setup" ] && ! [ -L "$setup" ]; then
-    echo "Moving regular file $setup to $setup.old for compatibility reasons." >&2
-    mv -f "$setup" "$setup".old
-fi
-
-echo "Creating symlink from $setup to $agent for compatibility reasons." >&2
-ln -sf "$agent" "$setup"
-
 echo "Ensuring that enable-threads is present in waptserver.ini" >&2
 tmpfile=$(mktemp)
 cat > "$tmpfile" << 'EOF'
@@ -69,5 +40,34 @@ except Exception:
 EOF
 python "$tmpfile"
 rm -f "$tmpfile"
+
+if [ -f "/opt/wapt/waptserver/waptserver.ini" ]
+then
+  if ps aux | grep -q wapt
+  then
+    [ -f /etc/init.d/waptserver ] && /etc/init.d/waptserver stop
+    # XXX temporary: clean up leftover waptserver processes
+    # due to broken /etc/init.d/waptserver script
+    pkill -INT -f '^/usr/bin/uwsgi-core.*wapt'
+    [ -f /etc/init.d/waptserver ] && /etc/init.d/waptserver start
+  else
+    [ -f /etc/init.d/waptserver ] && /etc/init.d/waptserver start
+  fi
+else
+    printf '\e[1;31m%-6s\e[m\n' "The installation of waptserver is finished !!"
+    printf '\e[1;31m%-6s\e[m\n' "For postconf please run: /usr/bin/python /opt/wapt/waptserver/scripts/postconf.py"
+fi
+
+# Backward compat
+agent=/var/www/wapt/waptagent.exe
+setup=/var/www/wapt/waptsetup.exe
+
+if [ -e "$setup" ] && ! [ -L "$setup" ]; then
+    echo "Moving regular file $setup to $setup.old for compatibility reasons." >&2
+    mv -f "$setup" "$setup".old
+fi
+
+echo "Creating symlink from $setup to $agent for compatibility reasons." >&2
+ln -sf "$agent" "$setup"
 
 exit 0
